name: GitHub Actions Demo
run-name: ${{ github.actor }} is so fucking sexy!

on:
  push:
    branches:
      - main
      - feature

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Login to Dockerhub
  #       uses: docker/login-action@v3
  #       with:
  #         registry: index.docker.io
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Pull repository 
  #       uses: actions/checkout@v4
  #     -
  #       name: Update and clone submodules
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{secrets.GH_PRIVATE_KEY}}" > ~/.ssh/actions-key
  #         sudo chmod 600 ~/.ssh/actions-key
  #         eval `ssh-agent -s`
  #         ssh-add ~/.ssh/actions-key
  #         git submodule update --remote --init
  #     -
  #       name: Build and push image to registry
  #       run: |
  #         docker compose build
  #         docker compose push
  deploy: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Set environment variables
        run: |
          export INSTANCE_IP=${{secrets.INSTANCE_IP}}
          export INSTANCE_HOST=ec2-user
          mkdir -p ~/.ssh
          echo "${{secrets.AWS_PRIVATE_KEY}}" > ~/.ssh/aws_key.pem
          sudo chmod 600 ~/.ssh/aws_key.pem
          alias bonk='ssh -i ~/.ssh/aws_key.pem $INSTANCE_HOST@$INSTANCE_IP'
          touch ~/konseki.txt
      -
        name: Test alias
        run: echo hello


  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "We are running bois!"