name: GitHub Actions Demo
run-name: ${{ github.actor }} is so fucking sexy!

on:
  push:
    branches:
      - main
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Save Github public key
        run : |
          mkdir ~/.ssh
          echo '${{ secrets.GH_PRIVATE_KEY }}' > ~/.ssh/gitkey
          chmod 600 ~/.ssh/gitkey
          ssh-agent -s
          ssh-add ~/.ssh/gitkey
      -
        name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: index.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Update and pull submodules
        uses: actions/checkout@v4
      -
        name: Update and pull submodules
        run: git submodule update --remote --init
      -
        name: Build and push image to registry
        run: |
          ls .
          ls portfolio-server
          ls portfolio-revised
          docker-compose -v

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "We are running bois!"